### ISSUE TITLE
A bit strange function signature

### ISSUE THREAD

**Issue by dmfv** [Villhard/TestAttest#1]
https://github.com/Villhard/TestAttest/blob/4b6254caa93069bd287958fa75becceca49441ea/database/user_connect.py

```
def check_user_exists(tg_id: int) -> User | None:
    """Проверка на существование пользователя в базе данных."""
    with Session() as session:
        user = session.query(User).filter(User.tg_id == tg_id).first()
        return user
```

function `check_user_exists` has a bit strage signature or name.
it's better to call it `get_user` which can return same (User | None)
in my opinion `check_user_exists` should return bool because it's just check

**Comment by Villhard** [comment]
Thank you. You're right.

**Comment by Villhard** [comment]
Thank you. You're right.
